apiVersion: v1
kind: Service
metadata:
  name: app-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: app-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-postgres
spec:
  serviceName: "app-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: app-postgres
  template:
    metadata:
      labels:
        app: app-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "web_shop"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-postgres-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-postgres-secret
              key: password
        volumeMounts:
        - name: app-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "500m"

  volumeClaimTemplates:
  - metadata:
      name: app-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
